# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: azd-get-started-with-ai-agents
metadata:
  template: azdc-get-started-with-ai-agents@0.0.1-beta

services:
  api:
    project: ./src
    language: py
    host: containerapp
    docker:
      remoteBuild: true
pipeline:
  variables:
    - AZURE_RESOURCE_GROUP
    - AZURE_AIHUB_NAME
    - AZURE_AIPROJECT_NAME
    - AZURE_AISERVICES_NAME
    - AZURE_SEARCH_SERVICE_NAME
    - AZURE_APPLICATION_INSIGHTS_NAME
    - AZURE_CONTAINER_REGISTRY_NAME
    - AZURE_KEYVAULT_NAME
    - AZURE_STORAGE_ACCOUNT_NAME
    - AZURE_LOG_ANALYTICS_WORKSPACE_NAME
    - USE_CONTAINER_REGISTRY
    - USE_APPLICATION_INSIGHTS
    - USE_SEARCH_SERVICE
    - AZURE_AI_AGENT_NAME
    - AZURE_AI_AGENT_ID
    - AZURE_AI_AGENT_DEPLOYMENT_NAME
    - AZURE_AI_AGENT_DEPLOYMENT_SKU
    - AZURE_AI_AGENT_DEPLOYMENT_CAPACITY
    - AZURE_AI_AGENT_MODEL_NAME
    - AZURE_AI_AGENT_MODEL_FORMAT
    - AZURE_AI_AGENT_MODEL_VERSION
    - AZURE_AI_EMBED_DEPLOYMENT_NAME
    - AZURE_AI_EMBED_DEPLOYMENT_SKU
    - AZURE_AI_EMBED_DEPLOYMENT_CAPACITY
    - AZURE_AI_EMBED_MODEL_NAME
    - AZURE_AI_EMBED_MODEL_FORMAT
    - AZURE_AI_EMBED_MODEL_VERSION
    - AZURE_AI_EMBED_DIMENSIONS
    - AZURE_AI_SEARCH_INDEX_NAME
    - AZURE_EXISTING_AIPROJECT_CONNECTION_STRING
    - AZURE_EXISTING_AIPROJECT_CONNECTION_STRING
resources:
  ai-project:
    type: ai.project
    connStringFromEnvVar: AZURE_EXISTING_AIPROJECT_CONNECTION_STRING
  api:
    type: host.containerapp
    uses:
      - ai-project
    port: 50505
    env:
     #  Required ENV VARS for the app to run
     #  AZURE_AIPROJECT_CONNECTION_STRING is automatically set by azd
     - name: AZURE_AI_AGENT_NAME
       value: agent-template-assistant
     - name: AZURE_AI_AGENT_DEPLOYMENT_NAME
       value: gpt-4o-mini
     - name: RUNNING_IN_PRODUCTION
       value: "true"

