name: Make Shell Scripts Executable on Merge to Main

on:
  push:

jobs:
  make-executable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make all .sh files executable
        run: |
          find . -type f -name "*.sh" -exec chmod +x {} \;